Все задачи модуля 2
js-tasks-ru/js-20230223_forumgm18 pull request #2
Opened 2023-02-28 07:42 UTC by forumgm18

2023-02-28 07:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-01 09:07 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      return ar.sort((a, b) => a.localeCompare(b, undefined,{ caseFirst: 'upper' }));
строка 11 дублирует строку 13 - это нужно устранить

2023-03-01 09:07 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      return ar.sort((a, b) => a.localeCompare(b, undefined,{ caseFirst: 'upper' })).reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2023-03-01 09:08 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
>  export const pick = (obj, ...fields) => {
проверьте что вернет вот такой вызов:
```js
pick({}, 'constructor');
```

Почему?

2023-03-01 09:09 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
>  export const omit = (obj, ...fields) => {
👍 good

2023-03-01 09:09 UTC, dosandk requested changes
Решения sortStrings и pick следует поправить

2023-03-01 16:24 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-02 12:17 UTC, dosandk approved these changes
👍 good

2023-03-02 12:17 UTC, merged